# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Inlined Dependencies (topologically sorted)
# ===============================================

# move_all_items_from_container (from core_player.py)
def move_all_items_from_container(sourceSerial, destinationSerial):
    for item in Items.FindBySerial(sourceSerial).Contains:
        Player.HeadMessage(455, "Moving item {}".format(item.Name))
        Items.Move(item, destinationSerial, item.Amount)
        Misc.Pause(800)

# ===============================================
# Main Script Code
# ===============================================
# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2024-03-26
# Use at your own risk. 

from Scripts.omgarturo.fm_core.core_player import move_all_items_from_container

# Moves all number of items from container 1 to container 2
# Prompts for source container.
# Prompts for destination container.

sourceSerial = Target.PromptTarget("Pick source container")
destinationSerial = Target.PromptTarget("Pick target container")

# have to do this or it wont find items
Items.UseItem(sourceSerial)
Misc.Pause(650)
Items.UseItem(destinationSerial)
Misc.Pause(650)
    
move_all_items_from_container(sourceSerial, destinationSerial)
