# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# External Imports
# ===============================================
from System import Byte, Int32
from System.Collections.Generic import List

# ===============================================
# Inlined Dependencies (topologically sorted)
# ===============================================

# get_pets (from core_mobiles.py)
def get_pets(range = 10, checkLineOfSight = True, mobileId = None):
    pets = []
    fil = Mobiles.Filter()
    fil.Enabled = True
    fil.RangeMax = range
    fil.Notorieties = List[Byte](bytes([1, 2]))
    fil.IsGhost = False
    fil.Friend = False
    fil.CheckLineOfSight = checkLineOfSight
    
    if mobileId is not None:
        fil.Bodies = List[Int32]([mobileId])
    
    blues = Mobiles.ApplyFilter(fil)    
    for blue in blues:
        if blue.CanRename:
            pets.append(blue)
    return pets

# ===============================================
# Main Script Code
# ===============================================
# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-08-24
# Use at your own risk. 

from Scripts.omgarturo.fm_core.core_mobiles import get_pets

# Clicks the hitching post and targets a pet at moonglow zoo
# so you dont have to.
# WARNING: THIS SCRIPT IS DANGEROUS! You can lose your pet!

pets = get_pets()

for pet in pets:
    Items.UseItem(0x401C023F)
    Target.WaitForTarget(3000)
    Target.TargetExecute(pet)
    Gumps.WaitForGump( 0x4a47a6eb,3000)
    Gumps.SendAction(0x4a47a6eb,1)
    Misc.Pause(1000)
