# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# External Imports
# ===============================================
from System import Byte, Int32
from System.Collections.Generic import List

# ===============================================
# Inlined Dependencies (topologically sorted)
# ===============================================

# get_yellows_in_range (from core_mobiles.py)
def get_yellows_in_range(range = 8):
    fil = Mobiles.Filter()
    fil.Enabled = True
    fil.RangeMax = range
    fil.Notorieties = List[Byte](bytes([7]))
    fil.IsGhost = False
    fil.Friend = False
    fil.CheckLineOfSight = False
    mobs = Mobiles.ApplyFilter(fil)

    return mobs

# ===============================================
# Main Script Code
# ===============================================
# Finds nearest yellow npc and opens the talk contextual menu.
# Use this for doing quests if you cant be bothered to click on an NPC.

TALK_CONTEXT = 0x00001500

npcs = get_yellows_in_range(range = 1)
if len(npcs) > 0:
    print(npcs[0].Name)
    Misc.UseContextMenu(npcs[0].Serial,"Talk",3000)
    Misc.Pause(1000)

#Misc.WaitForContext(TALK_CONTEXT, 10000)
#Misc.ContextReply(TALK_CONTEXT, 1)
