# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
Player.HeadMessage(38, "Training Animal Taming Using Mastery")

PET_SERIAL = 0x000EB0F7;

while not Player.IsGhost:
    Spells.CastMastery("Combat Training")
    Target.WaitForTarget(10000, False)
    Target.TargetExecute(PET_SERIAL)
    Misc.Pause(5000)
