# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
while Player.GetSkillValue('Bushido') < Player.GetSkillCap('Bushido'):
    Spells.CastMastery("Shield Bash")
    Misc.Pause(4000)
