# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
Player.HeadMessage(38, "Training Resisting Spells")
Player.HeadMessage(38, "NOT IMPLEMENTED YET")


while Player.GetRealSkillValue("Resisting Spells") < 100:
    skillValue = Player.GetRealSkillValue("Resisting Spells")
