# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-17
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
CAST_TIMEOUT = 700

def SelfCast(spell, wait_for_target = True):
    Spells.CastMagery(spell)
    if wait_for_target:
        Target.WaitForTarget(10000, False)
        Target.Self()
    
def Meditate():
    if Player.Mana != Player.ManaMax:
        Player.UseSkill("Meditation")

    #print("Pausing while we meditate")
    Misc.Pause(3000)
    while Player.BuffsExist('Meditation') and Player.Mana != Player.ManaMax:
        Misc.Pause(1000)

while Player.GetSkillValue("Evaluating Intelligence") < Player.GetSkillCap('Evaluating Intelligence'):
    if Player.Mana <= 23:
        Meditate()
    else:
        if Player.GetSkillValue("Magery") < 60:
            SelfCast("Mana Drain")
            Misc.Pause(CAST_TIMEOUT)
        elif Player.GetSkillValue("Magery") < 80:
            SelfCast("Reveal")
            Misc.Pause(CAST_TIMEOUT)
        elif Player.GetSkillValue("Magery") < 80:
            SelfCast("Mana Vampire")
            Misc.Pause(CAST_TIMEOUT)
        else:
            Player.HeadMessage(123, "Casing earthquake")
            #SelfCast("Earthquake", False)
            Spells.CastMagery("Earthquake")
            Misc.Pause(5000)
