# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# External Imports
# ===============================================
from System import Byte, Int32
from System.Collections.Generic import List

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
# Change serials. This needs work to make it usable by anyone.
# Converts cotton via a loom to spools of thread.

while True:
    items = Items.FindAllByID(0x0DF9, -1, Player.Backpack.Serial, -1, False)
    if len(items) > 0:
        Items.UseItem(items[0])
        Target.WaitForTarget(10000, False)
        Target.TargetExecute(0x40297EDA)
        Misc.Pause(5000)
    else:
        break
