# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ##########################################################
# #                                                        #
# #              INLINED DEPENDENCIES                     #
# #                                                        #
# #  DO NOT EDIT THIS SECTION - AUTO-GENERATED CODE       #
# #                                                        #
# #  These are dependencies from fm_core that have been   #
# #  automatically inlined. For user-editable code,       #
# #  scroll down to the bottom of this file.              #
# #                                                        #
# ##########################################################

# get_corpses (from core_items.py)
def get_corpses(range = 2):
    filter = Items.Filter()
    filter.OnGround = True
    filter.RangeMax = range
    filter.IsCorpse = True
    return Items.ApplyFilter(filter)

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
# Trains Forensic Eval

# 0 - 30 from trainer
# 30 - 55 corpses
# 55+ chests?

while Player.GetSkillValue('Forensic Evaluation') < 55:
    corpses = get_corpses(1)
    for corpse in corpses:
        Player.UseSkill("Forensics")
        Target.WaitForTarget(10000, False)
        Target.TargetExecute(corpse.Serial)
        Misc.Pause(1000)

# Just plugging in a chest serial for now.        
while Player.GetSkillValue('Forensic Evaluation') < Player.GetSkillCap('Forensic Evaluation'):
    Player.UseSkill("Forensics")
    Target.WaitForTarget(10000, False)
    Target.TargetExecute(0x4106C85D)
    Misc.Pause(1000)
