# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
while Player.GetSkillValue("Meditation") < Player.GetSkillCap('Meditation'):
#    Items.Move(0x40592F27, 0x41095E16, 1)
#    Misc.Pause(1000)
#    Player.EquipItem(0x40592F27)
#    Misc.Pause(3000)



    Spells.CastMagery("Earthquake")
    Misc.Pause(5000)
    Player.UseSkill("Meditation")
    Misc.Pause(3000)
    while Player.BuffsExist('Meditation') and Player.Mana != Player.ManaMax:
        Misc.Pause(1000)
