# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
Player.HeadMessage(38, "Training Animal Taming Using Mastery")

PET_SERIAL = 0x000EB0F7;

while not Player.IsGhost:
    Spells.CastMastery("Combat Training")
    Target.WaitForTarget(10000, False)
    Target.TargetExecute(PET_SERIAL)
    Misc.Pause(5000)
