# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-18
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
backpackSerial = Target.PromptTarget("Pick a bagpack to snoop, should be another player in guild")    
while Player.GetSkillValue("Snooping") < Player.GetSkillCap('Snooping'):  
    Items.UseItem(backpackSerial)
    Misc.Pause(1000)
