# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-18
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
while Player.GetSkillValue("Stealth") < 60: 

    if Player.Visible:
        Target.Cancel()        
        Player.UseSkill("Hiding")
        Misc.Pause(3000)

    while not Player.Visible:
        Player.Walk("North")
        Player.Walk("North")
        Player.Walk("East")
        Player.Walk("East")
        Player.Walk("East")
        Player.Walk("South")
        Player.Walk("South")
        Player.Walk("West")
        Player.Walk("West")
        Player.Walk("West")
        
    Misc.Pause(400)
    
sys.exit()
