# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-18
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# External Imports
# ===============================================
from System import Byte, Int32
from System.Collections.Generic import List
import sys
import time

# ===============================================
# Main Script Code
# ===============================================
# 0-30 trainer
# 30-80 i went to compassion desert and disco scorpions and spiders - spiders stop giving gains around 70 something
# 80-120 do cus, if you are good karma they dont get aggro
# also, if doing cus you never need to get discorded yourself
# if spending is not a problem
# get a token and 0-90 with that
# and only do cus
# and then soulstone

Misc.SendMessage("Training Discoteca")

INSTRUMENT_STATIC_IDS = [ 
    0x0E9C, # drum
    0x2805, # flute
    0x0EB3, # lute
    0x0EB2, # lap harp
    0x0EB1, # standing harp
    0x0E9E, # tambourine
    0x0E9D, # tambourine (tassle)
]

while Player.GetRealSkillValue("Discordance") <  Player.GetSkillCap('Discordance'):
    
    Target.Cancel()
# Noterieties:  blue = 1, green = 2, gray = 3, gray crim = 4, orange = 5, red = 6, yellow = 7
    fil = Mobiles.Filter()
    fil.Enabled = True
    fil.RangeMax = 8
    fil.Notorieties = List[Byte](bytes([3,4,5,6]))
    fil.IsGhost = False
    
    fil.Friend = False
    fil.CheckLineOfSight = False
    fil.Name = "a cu sidhe"
    mobs = Mobiles.ApplyFilter(fil)
    mob = Mobiles.Select(mobs,"Nearest")
    
    #mob = Mobiles.FindBySerial(0x0003F53A)
    if mob != None:
        #Items.FindAllByID(itemid,color,container,range,considerIgnoreList)
        instruments = Items.FindAllByID(itemids = INSTRUMENT_STATIC_IDS, color = -1, container = Player.Backpack.Serial, range = 1)
        #instruments = Items.FindAllByID(INSTRUMENT_STATIC_IDS, -1, -1, 3)
        if len(instruments) > 0:
            Items.UseItem(instruments[0])
            Misc.Pause(1000)
            Player.UseSkill("Discordance")
            Target.WaitForTarget(1500)
            Target.TargetExecute(mob)
        
            Misc.Pause(4000)
        else:
            print("No instrument found, quitting")
            sys.exit()
    else:
        print("No monsters found")
        Misc.Pause(30000)
        
        
    Misc.Pause(1500)
