# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
while Player.GetSkillValue("Hiding") < Player.GetSkillCap('Hiding'):
    Player.UseSkill("Hiding")
    Misc.Pause(3000)
    
while Player.GetSkillValue("Stealth") < Player.GetSkillCap('Stealth'):
    if Player.Visible:
        Target.Cancel()        
        Player.UseSkill("Hiding")
        Misc.Pause(3000)
        
    if not Player.Visible:
        Player.UseSkill("Stealth")
        Misc.Pause(3000)

    Misc.Pause(400)    
