# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-19
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ##########################################################
# #                                                        #
# #                 USER EDITABLE CODE                    #
# #                                                        #
# #  This is the original script code that you can        #
# #  modify and customize. Edit the parameters, logic,    #
# #  and function calls below as needed for your setup.   #
# #                                                        #
# #  The dependencies above have been automatically       #
# #  inlined and should not be modified.                  #
# ##########################################################

# ===============================================
# Main Script Code
# ===============================================
MSG = "Pick an NPC to beg from"
Player.HeadMessage(128, MSG)
npc = Mobiles.FindBySerial(Target.PromptTarget(MSG))

while Player.GetSkillValue('Begging') < Player.GetSkillCap('Begging'):
    Player.UseSkill("Begging")
    Target.WaitForTarget(10000, False)
    Target.TargetExecute(npc)
    Misc.Pause(3000)
