# Razor Enhanced Scripts for Ultima Online by
#   GRL  
#   https://github.com/GloriousRedLeader/omgarturo
#   2025-09-18
# Use at your own risk. 
#
# This file was auto-generated by the import inliner.
# Original dependencies from fm_core have been inlined below.

# ===============================================
# Main Script Code
# ===============================================
Player.HeadMessage(38, "Training Spirit Speak")

while not Player.IsGhost and Player.GetSkillValue('Spirit Speak') < 120:
    #Player.UseSkill("Spirit Speak")
    Spells.CastNecro('Vampiric Embrace')
    
    Misc.Pause(3500) 
